// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smwhphndqtmzgyjtlisb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtd2hwaG5kcXRtemd5anRsaXNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MzE0MDIsImV4cCI6MjA2NzEwNzQwMn0.PD4fFzS3DjgumQ_tsE0CcehO1rhr4D5aELytkFwQMd4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});